name = "flaregram"
main = "src/index.js"
compatibility_date = "2023-05-18"
env = { }

[dev]
host = "localhost"

[vars]
########## flaregram ###########
#  ---- See Wiki for all env variable descriptions.

# Mandatory Variables
REPO_VERSION = "1.0.1"
BOT_TOKEN = "7315028360:AAErdxTrUwKHI5aaw8wdpheex-LASw23Uhw"
WEBHOOK_URL = ""

# Optional Variables
SECRET_TOKEN = ""
DROP_PENDING_UPDATES = "True"

##################################
